config/routes.rb
FinexApp::Application.routes.draw do
  resources :stocks
  resources :bids
  resources :asks

  root to: 'static_pages#home'

  match '/stocks',  to: 'stocks#index'
  match '/add',  to: 'stocks#new'
  match '/buy',  to: 'bids#new'
  match '/sell',  to: 'asks#new'
  match '/stocks/:id/prices.js', to: 'stocks#prices'
  match '/stocks/:id/buys.js', to: 'stocks#buys'
  match '/stocks/:id/sells.js', to: 'stocks#sells'
  match '/stocks/:id/currentPrice.js', to: 'stocks#currentPrice'

end

app/models/ask.rb
class Ask < ActiveRecord::Base
  attr_accessible :price, :quantity, :stock_id, :status

  belongs_to :stock

  validates :price, presence: true  
  validates :quantity, presence: true  
  validates :stock_id, presence: true
  validates :status, presence: true
  
  default_scope order: 'asks.created_at DESC'

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  attr_accessible :price, :quantity, :stock_id, :status
  
  belongs_to :stock

  validates :price, presence: true  
  validates :quantity, presence: true  
  validates :stock_id, presence: true
  validates :status, presence: true
  
  default_scope order: 'bids.created_at DESC'
 
end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id         :integer          not null, primary key
#  ticker     :string(255)
#  name       :string(255)
#  quantity   :integer
#  price      :decimal(, )
#  priceUnit  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Stock < ActiveRecord::Base
  attr_accessible :name, :price, :priceUnit, :quantity, :ticker

  has_many :bids
  has_many :asks  
  has_many :stock_prices
  
  before_save {|stock| stock.ticker = ticker.upcase}
  
  validates :name, presence: true, length: {maximum: 255}
  validates :ticker, presence: true, length: {maximum: 255}, uniqueness: {case_sensitive: false}
  
  
  
  
end

app/models/stock_price.rb
class StockPrice < ActiveRecord::Base
  
  MATCH_BID_ASK_QUERY = "select b.id, a.id, b.stock_id, b.created_at, a.created_at from bids b, asks a where b.stock_id = a.stock_id and b.price = a.price
                                   and b.status = 200 and a.status = 200 order by b.created_at, a.created_at ASC";
  
  attr_accessible :ask_id, :bid_id, :price, :price_unit, :quantity, :transaction_time
  
  belongs_to :stock
  
  validates :stock_id, presence: true
  validates :bid_id, presence: true
  validates :ask_id, presence: true
  validates :price, presence: true
  validates :transaction_time, presence: true
  validates :quantity, presence: true
  
  default_scope order: 'stock_prices.transaction_time DESC'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  
  def show
    @ask = Ask.find(params[:id])
  end
  
 def new
    @ask = Ask.new
  end
  
  def create
    @ask = Ask.new(params[:ask])
    @ask.status = 200
    @ask.price_unit = 300;
    if @ask.save
      # Handle a successful save.
      flash[:success] = "Ask created successfully!"
      redirect_to @ask
    else
      render 'new'
    end
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  
  def show
    @bid = Bid.find(params[:id])
  end
  
 def new
    @bid = Bid.new
  end
  
  def create
    @bid = Bid.new(params[:bid])
    @bid.status = 200
    @bid.price_unit = 300;
    if @bid.save
      flash[:success] = "Bid created successfully!"
      redirect_to @bid
    else
      render 'new'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def show
    @stock = Stock.find(params[:id])
  end

  def new
    @stock = Stock.new
  end

  def index
    @stocks = Stock.all
  end

  def prices
    @stock = Stock.find(params[:id])
    @stock_prices = @stock.stock_prices
  end

  def buys
    @stock = Stock.find(params[:id])
    @bids = @stock.bids
  end

  def sells
    @stock = Stock.find(params[:id])
    @asks = @stock.asks
  end

  def currentPrice
    @stock = Stock.find(params[:id])
  end

  def create
    @stock = Stock.new(params[:stock])
    if @stock.save
      # Handle a successful save.
      flash[:success] = "Stock created successfully!"
      redirect_to @stock
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Financial Exchange App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/asks/_ask.html.erb
<% if ask.status == 200 %> 
<div class="clear"></div>
<div>
	<div class="span1">
		<%= ask.price %>
	</div>
	<div class="span1">
		<%= ask.quantity %>
	</div>
	<div class="span3">
		<%= time_ago_in_words(ask.created_at)%> ago.
	</div>
</div>
<% end %>

<% if ask.status == 210 %>
<div class="clear"></div>
<div style="background-color: #FF7171; color: #FFF; overflow: hidden;">
	<div class="span1">
		<%= ask.price %>
	</div>
	<div class="span1">
		-
	</div>
	<div class="span3">
		<%= time_ago_in_words(ask.created_at)%> ago.
	</div>
</div>
<% end %>

app/views/asks/_error_messages.html.erb
<% if @ask.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@ask.errors.count, "error") %>.
    </div>
    <ul>
    <% @ask.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/asks/new.html.erb
<% provide(:title, 'Add new ask') %>
<h1>Sell Stock</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@ask) do |ask| %>
    
    <%= render 'error_messages' %>

      <%= ask.label :quantity %>
      <%= ask.text_field :quantity %>

      <%= ask.label :price %>
      <%= ask.text_field :price %>

	  <%= ask.label :stock_id %>
	  <%= collection_select(:ask, :stock_id, Stock.all, :id, :name, {include_blank: 'Select Stock Name'}, {class: 'selectpicker'}) %>
	  
      <%= ask.submit "Place order", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/asks/show.html.erb
<% provide(:title, @ask.stock.name) %>
<div class="row">
  <aside class="span4">
    <section>
        <h1><%= @ask.stock.name%></h1>
		<h5>Ask placed for <%= @ask.stock.ticker %> for <%= @ask.quantity %> units at <%= @ask.price %> on <%= @ask.created_at %></h5>	
    </section>
  </aside>
</div>
<div class="center">
	<%= link_to "Buy", buy_path, class: "btn btn-large btn-primary" %>
	<%= link_to "Sell", sell_path, class: "btn btn-large btn-primary" %>
</div>

app/views/bids/_bid.html.erb
<% if bid.status == 200 %>
<div class="clear"></div>
<div>
	<div class="span1">
		<%= bid.price %>
	</div>
	<div class="span1">
		<%= bid.quantity %>
	</div>
	<div class="span3">
		<%= time_ago_in_words(bid.created_at)%> ago.
	</div>
</div>
<% end %>

<% if bid.status == 210 %>
<div class="clear"></div>
<div style="background-color: #FF7171; color: #FFF; overflow: hidden;">
	<div class="span1">
		<%= bid.price %>
	</div>
	<div class="span1">
		-
	</div>
	<div class="span3">
		<%= time_ago_in_words(bid.created_at)%> ago.
	</div>
</div>
<% end %>


app/views/bids/_error_messages.html.erb
<% if @bid.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@bid.errors.count, "error") %>.
    </div>
    <ul>
    <% @bid.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/bids/new.html.erb
<% provide(:title, 'Add new buy') %>
<h1>Buy Stock</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@bid) do |bid| %>
    
    <%= render 'error_messages' %>

      <%= bid.label :quantity %>
      <%= bid.text_field :quantity %>

      <%= bid.label :price %>
      <%= bid.text_field :price %>
      
      <%= bid.label :stock_id %>
	  <%= collection_select(:bid, :stock_id, Stock.all, :id, :name, {include_blank: 'Select Stock Name'}, {class: 'selectpicker'}) %>

      <%= bid.submit "Place order", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bids/show.html.erb
<% provide(:title, @bid.stock.name) %>
<div class="row">
	<aside class="span12">
		<section>
			<h1><%= @bid.stock.name%></h1>
			<h5>Bid placed for <%= @bid.stock.ticker %> for <%= @bid.quantity %> units at <%= @bid.price %> on <%= @bid.created_at %></h5>
		</section>
	</aside>
</div>
<div class="center">
	<%= link_to "Buy", buy_path, class: "btn btn-large btn-primary" %>
	<%= link_to "Sell", sell_path, class: "btn btn-large btn-primary" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Arun Radhakrishnan
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "FinEx", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Add Stock",    add_path %></li>
              <li><%= link_to "Show Stock",    stocks_path %></li>              
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>

	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<br />
			<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>">
				<%= value %>
			</div>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @stock.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@stock.errors.count, "error") %>.
    </div>
    <ul>
    <% @stock.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Financial Exchange</h1>

  <h2>
    This is where you can transact on stocks.
  </h2>

  <%= link_to "Buy", buy_path, class: "btn btn-large btn-primary" %>
  <%= link_to "Sell", sell_path, class: "btn btn-large btn-primary" %>
</div>

app/views/stock_prices/_stock_price.html.erb
<div>
  <span class="span1"><%= stock_price.price %></span>
  <span class="span1"><%= stock_price.quantity %></span>
  <span class="timestamp">
    <%= time_ago_in_words(stock_price.transaction_time) %> ago.
  </span>
</div>

app/views/stocks/buys.js.erb
<% @bids.each do |bid| %>
<% if bid.status == 200 %>
<div class="clear"></div>
<div>
	<div class="span1">
		<%= bid.price %>
	</div>
	<div class="span1">
		<%= bid.quantity %>
	</div>
	<div class="span3">
		<%= time_ago_in_words(bid.created_at)%> ago.
	</div>
</div>
<% end %>

<% if bid.status == 210 %>
<div class="clear"></div>
<div style="background-color: #FF7171; color: #FFF; overflow: hidden;">
	<div class="span1">
		<%= bid.price %>
	</div>
	<div class="span1">
		-
	</div>
	<div class="span3">
		<%= time_ago_in_words(bid.created_at)%> ago.
	</div>
</div>
<% end %>

<% end %>

app/views/stocks/currentPrice.js.erb
<h4><%= @stock.price %></h4>

app/views/stocks/index.html.erb
<% provide(:title, 'Stock View') %>
<h1>Show Stock Price Variations</h1>

<div class="row">
  <div class="span6 offset3">
         
	  <%= collection_select(1, 1, Stock.all, :id, :name, {include_blank: 'Select Stock Name'}, {class: 'selectpicker', onchange: "window.location.href=document.URL + '/' + this.value"}) %>
    
  </div>
</div>

app/views/stocks/new.html.erb
<% provide(:title, 'Add new stock') %>
<h1>Add new stock</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@stock) do |st| %>
    
    <%= render 'shared/error_messages' %>

      <%= st.label :name %>
      <%= st.text_field :name %>

      <%= st.label :ticker %>
      <%= st.text_field :ticker %>

      <%= st.label :quantity %>
      <%= st.text_field :quantity %>

      <%= st.label :price %>
      <%= st.text_field :price %>

      <%= st.submit "Add new stock", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/stocks/prices.js.erb
<% @stock_prices.each do |stock_price| %>
<div>
		<span class="span1"><%= stock_price.price %></span>
		<span class="span1"><%= stock_price.quantity %></span>
		<span class="timestamp"> <%= time_ago_in_words(stock_price.transaction_time) %> ago. </span>
</div>
<div class="clear"></div>
<% end %>

app/views/stocks/sells.js.erb
<% @asks.each do |ask| %>
<% if ask.status == 200 %> 
<div class="clear"></div>
<div>
	<div class="span1">
		<%= ask.price %>
	</div>
	<div class="span1">
		<%= ask.quantity %>
	</div>
	<div class="span3">
		<%= time_ago_in_words(ask.created_at)%> ago.
	</div>
</div>
<% end %>

<% if ask.status == 210 %>
<div class="clear"></div>
<div style="background-color: #FF7171; color: #FFF; overflow: hidden;">
	<div class="span1">
		<%= ask.price %>
	</div>
	<div class="span1">
		-
	</div>
	<div class="span3">
		<%= time_ago_in_words(ask.created_at)%> ago.
	</div>
</div>
<% end %>

<% end %>

app/views/stocks/show.html.erb
<% provide(:title, @stock.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1><%= @stock.name%> ( <%= @stock.ticker %> ) </h1>
			<div id="stockPrice">
				<h4><%= @stock.price %></h4>
			</div>
		</section>
	</aside>
	<div class="span8">
		<% if @stock.stock_prices.any? %>
		<div class="span4">
			<h3>Price Variation</h3>
		</div>
		<div class="clear"></div>
		<div class="stock_prices">
			<div>
				<span class="span1">Price</span>
				<span class="span1">Quantity</span>
				<span class="timestamp">Transaction Time</span>
			</div>
			<div id="prices">
				<%= render @stock.stock_prices %>
			</div>
		</div>
		<% end %>
		<div class="clear" style="margin-bottom:70px;"></div>
	</div>
	
	<div class="span6" style="float:left">
		<div class="span6">
			Bids Placed
		</div>
		<div class="span1">
			Price
		</div>
		<div class="span1">
			Quantity
		</div>
		<div class="span3">
			Time
		</div>
		<div id="buys">
			<%= render @stock.bids %>
		</div>
	</div>
	<div class="span6" style="float:right">
		<div class="span6">
			Asks Placed
		</div>
		<div class="span1">
			Price
		</div>
		<div class="span1">
			Quantity
		</div>
		<div class="span3">
			Time
		</div>
		<div id="sells">
			<%= render @stock.asks %>
		</div>
	</div>
</div>
 <script type="text/javascript">

		$(document).ready(function() {
			setInterval(function(){
			$.get("/stocks/<%= @stock.id%>/prices.js", function(data){
					$("#prices").html(data);
				},"html")
			}, 3000);

		setInterval(function(){
		$.get("/stocks/<%= @stock.id%>/buys.js", function(data){
		$("#buys").html(data);
		}, "html")
		}, 3000);

		setInterval(function(){
		$.get("/stocks/<%= @stock.id%>/sells.js", function(data){
		$("#sells").html(data);
		}, "html")
		}, 3000);
		
		setInterval(function(){
		$.get("/stocks/<%= @stock.id%>/currentPrice.js", function(data){
		$("#stockPrice").html(data);
		}, "html")
		}, 3000);
		
		
		});
</script>